development:
  adapter: postgresql
  encoding: unicode
  database: ayako_page_development
  pool: 5
  username: dany
  password: pp34wf
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: ayako_page_test
  pool: 5
  username: dany
  password: pp34wf
  host: localhost
